language: elixir
elixir:
  - 1.2.4
notifications:
  recipients:
    - clive@whitemonkeysoftware.co.uk
otp_release:
  - 18.2.1
before_script:
  - mix local.hex --force
  - mix deps.get
script:
  - mix test
sudo: false
